name = "shisha-up"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# 環境変数をここに定義
ENVIRONMENT = "development"

# Cloudflare D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "gotoshisha-db"
database_id = "4ef2320c-4159-4c27-9a38-2c34be72f830"

# 本番環境用の設定
[env.production]
name = "shisha-up-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "gotoshisha-db-prod"
database_id = "80e2f98c-c266-41a6-b584-213727c6fb8c" # 本番用データベースID

# ステージング環境用の設定
[env.staging]
name = "shisha-up-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "gotoshisha-db-staging"
database_id = "" # ステージング用データベースID
