name = "shisha-up"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# 環境変数をここに定義
ENVIRONMENT = "development"

# Cloudflare D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "gotoshisha-db"
database_id = "4ef2320c-4159-4c27-9a38-2c34be72f830"


[[env.production.d1_databases]]
binding = "DB"
database_name = "gotoshisha-db"
database_id = "4ef2320c-4159-4c27-9a38-2c34be72f830"